# Vector & Matrix & Array 자료구조

- 연속된 1차원의 선형구조의 형태로 만들어짐
- 같은 자료형의 데이터만 저장할 수 있다.
- 첫 번째 셀에서 정수와 문자를 혼합하여 저장했지만 반환되는 건 모두 문자로 변환되어 반환된다.
- 첫 번째 셀과 두 번째 셀을 비교해보자

In [108]:
df=c(1,2,'ㅁㄴㅇ')
df

[1] "1"      "2"      "ㅁㄴㅇ"

In [109]:
df_=c(1,2,3)
df_

[1] 1 2 3

- 벡터 생성 함수 : c(), seq(), rep()
- 벡터 자료 처리 함수 : union(), setdiff(), intersect()

In [110]:
c(1:10)
1:10
c(1,2,3,4,5,6,7,8,9,10)

[1]  1  2  3  4  5  6  7  8  9 10

[1]  1  2  3  4  5  6  7  8  9 10

[1]  1  2  3  4  5  6  7  8  9 10

In [111]:
seq(1,10,3)
# 1부터 10까지 3씩 증가

[1]  1  4  7 10

In [112]:
rep(1:3,3)

[1] 1 2 3 1 2 3 1 2 3

In [113]:
rep(1,3)

[1] 1 1 1

In [114]:
rep(1:3,each=2)
# 각 자료가 반복

[1] 1 1 2 2 3 3

- 벡터 자료 처리

In [115]:
x<-c(1,2,3,4)
y<-c(2,3)
union(x,y) # 합집합
setdiff(x,y) # x-y

[1] 1 2 3 4

[1] 1 4

In [116]:
setdiff(y,x) # y-x는 남는 게 없음

numeric(0)

In [117]:
intersect(x,y) # 교집합

[1] 2 3

- 변수에 다양한 형식의 벡터 자료를 저장할 수 있다. 하지만 벡터 자료는 같은 유형의 자료만 하나의 변수에 저장할 수 있다.
- 만약 숫자형과 문자형 또는 논리형이 혼합되는 경우에는 데이터 유형이 변경될 수 있다.

In [118]:
v<-c(T,TRUE,F,FALSE)
v
v<-c(T,TRUE,F,FALSE,1)
v
v<-c(T,TRUE,F,FALSE,1,'1')
v

[1]  TRUE  TRUE FALSE FALSE

[1] 1 1 0 0 1

[1] "TRUE"  "TRUE"  "FALSE" "FALSE" "1"     "1"

- character <- numeric <- logical 순으로 우선순위를 두고 변경 됨
- R에서는 세미콜론(;)을 구분자로하여 한 줄에 여러 개의 R 스크립트 명령문을 사용할 수 있음

In [119]:
age=c(30,40,50)
age
names(age)=c('곽도성의 나이','곽도성2의 나이','곽도성3의 나이')
age
age<-NULL # NaN은 되긴 하지만 NULL과 의미가 다른가?
age

[1] 30 40 50

곽도성의 나이 곽도성2의 나이 곽도성3의 나이 
            30             40             50

NULL

- 위 셀처럼 벡터 객체의 값에 칼럼명 지정

In [120]:
a<-c(1:12)
a[1:5]

[1] 1 2 3 4 5

- 파이썬은 index 0번이 첫 번째 원소를 뜻하지만 R에서는 index 1이 첫 번째 원소를 뜻한다.

In [121]:
length(a)

[1] 12

- 벡터 객체에서 첨자를 이용하여 원소를 조회할 경우 c() 함수의 인수에 콤마를 사용할 수 있다. 이때 콤마는 1차원 자료구조에서 하나의 원소를 지정하는 역할을 한다. 

In [122]:
c1<-c(1,2,3,4,2:5)
c1
c1[c(1,3)]
c1[c(1:3)]

[1] 1 2 3 4 2 3 4 5

[1] 1 3

[1] 1 2 3

- 위 셀처럼 벡터 객체의 원소를 참조하기 위해서 c() 함수의 인수로 콤마와 콜론(:)을 이용할 수 있다. 콤마는 개별 원소 하나씩 지정하며 콜론은 원소의 범위를 지정하는 역할을 한다. 

In [123]:
c1

[1] 1 2 3 4 2 3 4 5

In [124]:
c1[-1]
c1[-c(2,4)]
c1[c(-2,-4)]
c1[c(-2:-4)]
c1[c(-4:-1)]

[1] 2 3 4 2 3 4 5

[1] 1 3 2 3 4 5

[1] 1 3 2 3 4 5

[1] 1 2 3 4 5

[1] 2 3 4 5

- index를 음수값으로 지정하는 경우에는 여집합의 개념으로 해당 첨자가 제외된다. 벡터 객체를 대상으로 위 셀처럼 c1[-1]을 지정할 경우 1번째만 제외하고 나머지 모든 벡터 자료가 반환된다. 

---

- Matrix : 동일한 자료형을 갖는 2차원의 배열구조를 갖는다. 
- 행과 열의 2차원 배열구조의 객체를 생성한다.
- 동일한 타입의 데이터만 저장할 수 있다.
- 행렬 생성 함수 : matrix(),rbind(),cbind()
- 행렬 자료 처리 함수 :apply()

In [125]:
m=matrix(c(1:5))
m

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5

- 위 셀처럼 matrix() 함수에서 c() 함수를 인수로 지정하여 matrix 객체를 생성할 수 있다. c() 함수는 `기본적으로 열을 기준`으로 객체를 만들어준다. 

In [126]:
m=matrix(1:10,nrow=2)
m
m=matrix(c(1:10),nrow=2)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

- 이렇게 일단 열 기준임!

In [127]:
m=matrix(c(1:11),nrow=3)
m

Warning message in matrix(c(1:11), nrow = 3):
"데이터의 길이[11]가 행의 개수[3]의 배수가 되지 않습니다"


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9     1

- 자료의 개수와 행과 열이 맞아 떨어지지 않으면 알아서 broadcast하여 채워 넣음

- 벡터 데이터를 대상으로 행렬 객체를 생성하면 기본적으로 열 우선으로 데이터가 생성된다.
- 행 우선으로 데이터를 생성해보자

In [128]:
m=matrix(1:10,nrow=2,byrow = T)
m
m=matrix(1:10,nrow=2,byrow = TRUE)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

- 행 또는 열 묶음으로 행렬 객체 생성해보자

In [129]:
x1<-c(1,2,3,6:10)
x2<-c(1,2,3,5:1)

In [130]:
bond<-rbind(x1,x2)
bond
bond<-cbind(x1,x2)
bond

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
x1 1    2    3    6    7    8    9    10  
x2 1    2    3    5    4    3    2     1

x1 x2
[1,]  1 1 
[2,]  2 2 
[3,]  3 3 
[4,]  6 5 
[5,]  7 4 
[6,]  8 3 
[7,]  9 2 
[8,] 10 1

- 각각 8개로 개수가 맞아서 rbind가 잘 됐음
- 개수 안 맞으면 bind 안 됨

---

- matrix() 함수에 직접 인수를 적용하여 행렬 객체를 생성할 수 있다. 
- matrix() 함수의 형식은 다음과 같다.
```r
matrix(data=NA,nrow =1, ncol=1, byrow=TRUE,dimnames=NULL)
```

In [131]:
m3=matrix(10:19,2)
m3

[,1] [,2] [,3] [,4] [,5]
[1,] 10   12   14   16   18  
[2,] 11   13   15   17   19

In [132]:
mode(m3)
class(m3)

[1] "numeric"

[1] "matrix" "array"

- index를 이용하여 행렬 객체에 접근하기

In [133]:
m3[1,] # 1행
m3[,3] # 3열
m3[1,3] # 1행 3열
m3[1,2:4]

[1] 10 12 14 16 18

[1] 14 15

[1] 14

[1] 12 14 16

In [134]:
matrix(1:9,nrow=3,byrow=T)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

- 행렬 객체 자료 처리 함수

In [135]:
length(m3)
# 원소 개수
ncol(m3)
# 열 개수
nrow(m3)
# 행 개수

[1] 10

[1] 5

[1] 2

- apply() 함수는 행렬 구조의 자료를 처리하는 데 유용한 함수이다.
- 함수 사용법 : apply(행렬객체, 1:행 or 2:열, 행렬 자료에 적용할 함수)

In [136]:
m3

[,1] [,2] [,3] [,4] [,5]
[1,] 10   12   14   16   18  
[2,] 11   13   15   17   19

In [137]:
apply(m3,1,max)
apply(m3,2,max)
apply(m3,1,mean)

[1] 18 19

[1] 11 13 15 17 19

[1] 14 15

- 당연히 사용자 정의 함수도 apply()에 사용할 수 있을 것이다.

- 이건 파이썬에서 함수 정의하는 방법이고
```python
def f(x):
    return(x+2)
```
- 이건 R에서 함수 정의하는 방법
```R
f <- function(x){
    x*c(1,2,3)}
```

In [138]:
f <- function(x){
    x*3}

In [139]:
m3

[,1] [,2] [,3] [,4] [,5]
[1,] 10   12   14   16   18  
[2,] 11   13   15   17   19

In [140]:
apply(m3,1,f)
# 행 우선 순위로 f함수 적용
# 벡터 데이터 연산할 때 열 단위로 결과 출력
# 벡터 자료와 연산하면 기본적으로 열 우선 순서로 출력된다.
# 이러한 행렬 구조를 전치행렬이라고 한다.

[,1] [,2]
[1,] 30   33  
[2,] 36   39  
[3,] 42   45  
[4,] 48   51  
[5,] 54   57

In [141]:
apply(m3,2,f)

[,1] [,2] [,3] [,4] [,5]
[1,] 30   36   42   48   54  
[2,] 33   39   45   51   57

---

- 벡터 객체 에서 이름 지정하기

In [142]:
age=c(30,40,50)
age
names(age)=c('곽도성의 나이','곽도성2의 나이','곽도성3의 나이')
age

[1] 30 40 50

곽도성의 나이 곽도성2의 나이 곽도성3의 나이 
            30             40             50

- 행렬 객체에서 이름 지정하기

In [143]:
m3

[,1] [,2] [,3] [,4] [,5]
[1,] 10   12   14   16   18  
[2,] 11   13   15   17   19

In [144]:
colnames(m3)=c(12,3,4,5,5)
m3

12 3  4  5  5 
[1,] 10 12 14 16 18
[2,] 11 13 15 17 19

---

- Array 자료구조 : 같은 자료형을 갖는 다차원 배열구조를 갖는다.
- 행, 열, 면의 3차원 배열 형태의 객체를 생성한다.
- 다른 자료구조에 비해서 상대적으로 활용도가 낮다.
- 배열 생성 함수 : array()                <*apply()와 혼동 주의>

In [155]:
vec=c(1:12)
arr <- array(vec,c(3,2,2))
arr
# 3행 2열 2면 생성

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

In [157]:
arr[,,1]
# 1면 조회
arr[,,2]
# 2먼 조회

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 7    10  
[2,] 8    11  
[3,] 9    12

In [159]:
mode(arr)
class(arr)

[1] "numeric"

[1] "array"

---

- DataFrame 자료구조 : R에서 가장 많이 활용
  - 데이터 베이스의 테이블 구조와 유사하다.
  - `칼럼 단위로 서로 다른 데이터의 저장이 가능`
  - 리스트와 벡터의 혼합형으로 칼럼은 리스트, 칼럼 내의 데이터는 벡터 자료 구조를 갖는다.
  - 데이터프레임 생성함수 : data.frame(),read.table(), read.csv()
  - 데이터프레임 자료 처리 함수 : str(), ncol(), nrow(), apply(), summary(), subset()

- 데이터 프레임은 열 단위로 서로 다른 자료형을 포함할 수 있어서 벡터와 행렬을 이용하여 데이터 프레임 객체를 생성할 수 있다.
- 기존의 데이터 파일을 불러와서 데이터 프레임 객체를 생성할 수도 있다.
- 사용법 : data.frame(칼럼1=자료, 칼럼2=자료, ...)

> 벡터를 이용한 데이터 프레임 객체 생성

In [172]:
no <- c(1:3)
name <- c('k','b','s')
pay <- c(150, 200, 300)
vemp <- data.frame(칼럼1 = no, 칼럼2 = name, 칼럼3 = pay)
vemp

칼럼1 칼럼2 칼럼3
1 1     k     150  
2 2     b     200  
3 3     s     300

In [176]:
vemp[1,1]

[1] 1

- 여러 개의 벡터 객체를 이용하여 데이터 프레임을 생성할 수 있다.
- 이때 각 벡터 객체의 칼럼 길이는 동일해야한다. 

> 매트릭스를 이용한 데이터프레임 객체 생성

In [182]:
m=matrix(c(1,"k",150,
           2,'b',200,
           3,'s',250)
           ,3,by=T)
memp=data.frame(m)
memp

X1 X2 X3 
1 1  k  150
2 2  b  200
3 3  s  250

In [183]:
memp[1,1]

[1] "1"

In [176]:
vemp[1,1]

[1] 1

- 애초에 매트릭스를 이용해 데이터 프레임 객체를 생성할 때 매트릭스는 동일한 자료밖에 안 되기에 안의 원소가 전부 character로 변경됐었지만 vemp는 상이한 벡터 객체들을 데이터 프레임을 통해서 모아놓은 것이기 떄문에 자료형이 변하지 않고 유지되었음

In [192]:
df = data.frame(x=1:5, y=seq(1,9,2),z=c('abfa','aavd','avs','S','S'))
df

x y z   
1 1 1 abfa
2 2 3 aavd
3 3 5 avs 
4 4 7 S   
5 5 9 S

- 데이터 프레임의 칼럼명 참조하기

In [194]:
df$x
df$y
df$z

[1] 1 2 3 4 5

[1] 1 3 5 7 9

[1] "abfa" "aavd" "avs"  "S"    "S"

- $는 데이터 프레임에선 칼럼을 의미하며 리스트에서는 키를 의미한다.