# data.frame, List, stringr

- data.frame 객체 자료 처리 함수

In [116]:
df = data.frame(x=1:5, y=seq(1,9,2),z=c('abfa','aavd','avs','S','S'))
df

x y z   
1 1 1 abfa
2 2 3 aavd
3 3 5 avs 
4 4 7 S   
5 5 9 S

In [117]:
str(df)
# 데이터 프레임의 구조를 보여준다. 

'data.frame':	5 obs. of  3 variables:
 $ x: int  1 2 3 4 5
 $ y: num  1 3 5 7 9
 $ z: chr  "abfa" "aavd" "avs" "S" ...


- 5 obs. of  3 variables : 5개의 관측치와 3개의 변수로 구성됨

In [118]:
ncol(df)

[1] 3

In [119]:
nrow(df)

[1] 5

In [120]:
# 칼럼명 반환
names(df)

[1] "x" "y" "z"

In [121]:
df[c(2,3),1]
# R은 파이썬과 달리 index가 1부터 시작함!

[1] 2 3

In [122]:
df[1]
# 첫 번째 열

x
1 1
2 2
3 3
4 4
5 5

In [123]:
summary(df)
# 요약 통계량을 볼 수 있다.
# 숫자로 구성된 칼럼에 대해서만 수행된다. 

       x           y          z            
 Min.   :1   Min.   :1   Length:5          
 1st Qu.:2   1st Qu.:3   Class :character  
 Median :3   Median :5   Mode  :character  
 Mean   :3   Mean   :5                     
 3rd Qu.:4   3rd Qu.:7                     
 Max.   :5   Max.   :9                     

In [124]:
df[,c(1,2)]

x y
1 1 1
2 2 3
3 3 5
4 4 7
5 5 9

In [125]:
df[c(1,2)]

x y
1 1 1
2 2 3
3 3 5
4 4 7
5 5 9

In [126]:
apply(df[,c(1,2)],2,sum)

x  y 
15 25

In [127]:
apply(df[c(1,2)],2,sum)

x  y 
15 25

- 데이터프레임의 부분 객체 만들기
  - 데이터 프레임 객체의 데이터를 대상으로 조건에 만족하는 행을 추출하여 독립된 객체를 생성할 수 있다.

In [128]:
x1 <- subset(df,x>=3)
x1

x y z  
3 3 5 avs
4 4 7 S  
5 5 9 S

- 행 기준이다.

In [129]:
x2 <- subset(df, x>=2 & y<=6)
x2

x y z   
2 2 3 aavd
3 3 5 avs

- 이렇게 두 개의 조건으로 부분 객체를 만들 수도 있다.

---

In [130]:
sid = c('a','b','c','d')
score = c(12,123,13,5)
subject = c('컴퓨터1','컴퓨터2','컴퓨터3','컴퓨터4')

student = data.frame(sid ,score, subject)
student

sid score subject
1 a    12   컴퓨터1
2 b   123   컴퓨터2
3 c    13   컴퓨터3
4 d     5   컴퓨터4

In [131]:
mode(student)
class(student)

[1] "list"

[1] "data.frame"

In [132]:
str(sid);str(score);str(subject);str(student)
# 벡터 자료구조와 데이터 프레임 자료구조

 chr [1:4] "a" "b" "c" "d"
 num [1:4] 12 123 13 5
 chr [1:4] "컴퓨터1" "컴퓨터2" "컴퓨터3" "컴퓨터4"
'data.frame':	4 obs. of  3 variables:
 $ sid    : chr  "a" "b" "c" "d"
 $ score  : num  12 123 13 5
 $ subject: chr  "컴퓨터1" "컴퓨터2" "컴퓨터3" "컴퓨터4"


---

In [133]:
h <- data.frame(id = c(1,2), height = c(123,1234))
w <- data.frame(id2 = c(1,2), weight = c(123,43))

In [134]:
h;w

id height
1 1   123  
2 2  1234

id2 weight
1 1   123   
2 2    43

In [135]:
merge(h,w,by.x='id',by.y='id2')

id height weight
1 1   123   123   
2 2  1234    43

- by.x='id',by.y='id2' -> 병합 시에 기준이 되는 칼럼명이 상이할 때 사용함

---

In [136]:
install.packages('UsingR') # 패키지 설치
library(UsingR) # 패키지 로드
data(galton) # galton 데이터 셋 가져오기

package 'UsingR' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\ehfus\AppData\Local\Temp\RtmpYpStoY\downloaded_packages


Loading required package: MASS

Loading required package: HistData

Loading required package: Hmisc

Loading required package: lattice

Loading required package: survival

Loading required package: Formula

Loading required package: ggplot2


Attaching package: 'Hmisc'


The following objects are masked from 'package:base':

    format.pval, units



Attaching package: 'UsingR'


The following object is masked from 'package:survival':

    cancer




In [137]:
str(galton)

'data.frame':	928 obs. of  2 variables:
 $ child : num  61.7 61.7 61.7 61.7 61.7 62.2 62.2 62.2 62.2 62.2 ...
 $ parent: num  70.5 68.5 65.5 64.5 64 67.5 67.5 67.5 66.5 66.5 ...


In [138]:
dim(galton)

[1] 928   2

In [139]:
head(galton, 5)

child parent
1 61.7  70.5  
2 61.7  68.5  
3 61.7  65.5  
4 61.7  64.5  
5 61.7  64.0

---

- List 자료구조
  - List는 성격이 다른 자료형(문자열, 숫자형, 논리형)과 자료구조(벡터, 행렬, 리스트, 데이터 프레임)를 객체로 생성할 수 있다.
  - 하나의 메모리 영역에는 키과 값이 한 쌍
  - Python의 dict 자료구조와 유사하다. 
  - list 생성 함수 : list()
  - list 자료 처리 함수 : unlist(), lapply(), sapply()
  - list는 키와 값을 한 쌍으로 하여 원소가 저장되는 자료구조이다. 만약 키를 생략하면 자동으로 기본 키가 생성된다.

In [140]:
list1 <- list('lee','lee2',95) # list 객체 생성
list1

[[1]]
[1] "lee"

[[2]]
[1] "lee2"

[[3]]
[1] 95

- key를 지정하지 않아서 임의로 지정됐음
- list 객체는 키를 통해서 값이 저장되기 때문에 서로 다른 자료형을 저장할 수 있다.
  - list와 data.frame은 상이한 자료형을 혼합할 수 있다.

- list를 vector로 변경해보자

In [141]:
unlist <- unlist(list1)
unlist

[1] "lee"  "lee2" "95"

- 리스트 자료구조에 다량의 데이터가 저장되는 경우 리스트 형태로 출력하면 여러 줄로 출력되기 때문에 벡터 형식으로 변환할 경우 자료 처리가 용이해진다. 
- `character > numeric > logical 순서로 벡터에 저장되기 때문에 전부 character로 변환하여 반환되었음`

In [142]:
list2 <- list(c(1:5),c(5:1))
list2

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] 5 4 3 2 1

In [143]:
list3 <- list(matrix(1:6,2),array(1:12,c(3,2,2)))
list3

[[1]]
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

[[2]]
, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

- `이렇게 list 객체의 value에 저장될 수 있는 자료구조는 VECTOR 뿐만이 아니라 matrix 혹은 array도 가능하다.`

---

- key 명명하자

In [144]:
list4 <- list(name = c('홍길동','유관순'), age = c(1234,1245))
list4

$name
[1] "홍길동" "유관순"

$age
[1] 1234 1245

In [145]:
list4$name
list4$name[2]

[1] "홍길동" "유관순"

[1] "유관순"

In [146]:
list4$age
list4$age[1]

[1] 1234 1245

[1] 1234

In [147]:
list4$age[1]<-1245 # 원소 수정 가능
list4$newkey <- 'asdf' # 새로운 키 추가
list4$newkey[c(1,2)] <- c(124,1255) # 새롭게 추가 된 키에 새로운 value 추가

In [148]:
list4

$name
[1] "홍길동" "유관순"

$age
[1] 1245 1245

$newkey
[1] "124"  "1255"

In [149]:
length(list4)
length(list4$name)
mode(list4)
class(list4)

[1] 3

[1] 2

[1] "list"

[1] "list"

In [150]:
list4$new<- NULL

In [151]:
list4

$name
[1] "홍길동" "유관순"

$age
[1] 1245 1245

$newkey
[1] "124"  "1255"

- 일부 key와 value 제거

In [152]:
list4 <- NULL

In [153]:
list4

NULL

- 모두 제거

---

- 리스트 객체의 자료 처리 함수

In [154]:
a = list(c(1:5))
b = list(c(6:10))
lapply(c(a,b),max) # 리스트 객체에 max 함수 적용

[[1]]
[1] 5

[[2]]
[1] 10

- lapply() 함수는 두 개의 리스트 객체 a와 b를 대상으로 max() 함수를 적용하여 각 리스트 객체의 자료 중에서 가장 큰 값을 리스트 형태로 반환한다. 
- 동일한 결과를 벡터 형식으로 반환해보자

In [155]:
sapply(c(a,b),max)

[1]  5 10

- lapply()는 연산 결과를 리스트 형태로 반환하지만, sapply()는 결과를 벡터형식으로 반환하기 때문에 많은 원소를 포함하고 있는 리스트 객체를 보다 효과적으로 처리할 수 있다.

---

- 다차원 리스트 객체를 생성해보자
  - 리스트 자료구조에 또 다른 리스트가 중첩된 자료구조를 다차원 리스트라고 한다.
  - 즉 value가 list이다

In [156]:
complex = list(c1 = list(1,2,3),
              c2 = list(4,5,6),
              c3 = list(7,8,9))
complex

$c1
$c1[[1]]
[1] 1

$c1[[2]]
[1] 2

$c1[[3]]
[1] 3


$c2
$c2[[1]]
[1] 4

$c2[[2]]
[1] 5

$c2[[3]]
[1] 6


$c3
$c3[[1]]
[1] 7

$c3[[2]]
[1] 8

$c3[[3]]
[1] 9

In [157]:
complex$c1

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

- 다차원 리스트를 열 단위로 바인딩하기

In [158]:
do.call(cbind, complex)

c1 c2 c3
[1,] 1  4  7 
[2,] 2  5  8 
[3,] 3  6  9

In [159]:
class(do.call(cbind, complex))

[1] "matrix" "array"

In [160]:
do.call(rbind, complex)

[,1] [,2] [,3]
c1 1    2    3   
c2 4    5    6   
c3 7    8    9

In [161]:
class(do.call(rbind, complex))

[1] "matrix" "array"

- 3개의 value를 구성하는 list 자료가 열 단위로 묶여서 matrix 객체가 생성된다. 특히 do.call() 함수는 다차원 리스트를 구성하는 리스트를 각각 분해한 후 지정된 함수(cbind 또는 rbind)를 호출하여 리스트 자료를 처리하는 데 효과적이다.

---

- 텍스트 자료나 SNS에서 가공 처리된 빅데이터를 처리하기 위해서는 필요한 문자열을 적절하게 자르고 교체하고 추출하는 작업이 중요하다. 문자열을 효과적으로 처리하는 stringr 패키지에 대해 알아보자

In [162]:
# 패키지 설치
install.packages('stringr')
library(stringr)

Warning message:
"package 'stringr' is in use and will not be installed"


In [163]:
str_extract("홍길동35이순신45유관순25","[1-9]{2}")
str_extract_all("홍길동35이순신45유관순25","[1-9]{2}")

[1] "35"

[[1]]
[1] "35" "45" "25"

- str_extract() 함수는 지정된 문자열을 대상으로 정규 표현식 '[1-9]{2}'의 패턴(숫자 2개가 연속된 경우)과 일치하는 가장 처음에 발견된 문자열을 추출해준다.
- str_extract_all는 지정된 문자열을 대상으로 정규 표현식 '[1-9]{2}'의 패턴(숫자 2개가 연속된 경우)과 일치하는 모든 문자열을 추출해준다.

---

- 정규 표현식
  - 문자열 처리 관련 함수는 대부분 정규표현식을 이용하여 문자열의 패턴을 검사하고 해당 문자열을 대상으로 문자열을 교체하거나 추출하게 된다. 정규표현식은 약속된 기호인 메타문자들에 의해 표현된다.

- 반복 관련 정규 표현식
  - []기호는 대괄호 안의 문자가 한 번만 반복되고, {n}은 n만큼 반복된다. 
    - 예를 들면 [a-z]의 정규 표현식은 영문 소문자 a에서 z까지 범위 중에서 한 개의 영문 소문자를 의미하고 [a-z]{3}은 영문 소문자가 연속으로 3개 발생한다는 의미이다.

In [164]:
string = 'rhkrehtjddms123 dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlek.'

In [165]:
str_extract_all(string, '[a-z]{4}')
# 영문 소문자가 4글자 연속하는 경우 추출

[[1]]
[1] "rhkr" "ehtj" "ddms" "rhdq" "nfmf" "xhde" "kfgk" "rjtd"

In [166]:
str_extract_all(string, '[a-z]{4,}')
# 영문 소문자가 4글자 **이상** 연속하는 경우 추출

[[1]]
[1] "rhkrehtjddms" "rhdqnfmf"     "xhdekfgkf"    "rjtdlek"

In [167]:
str_extract_all(string, '[a-z]{3,5}')
# 영문 소문자가 4글자 **이상** 5글자 **이하** 연속하는 경우 추출

[[1]]
[1] "rhkre" "htjdd" "rhdqn" "fmf"   "xhdek" "fgkf"  "rjtdl"

In [168]:
str_extract_all(string, 'rhkrehtjd')
# 해당 문자열 추출

[[1]]
[1] "rhkrehtjd"

In [169]:
str_extract_all(string,'2')
# 해당 숫자 추출

[[1]]
[1] "2"

In [170]:
str_extract_all(string,'[가-힣]{2,}')
# 연속된 3개 이상의 한글 문자열 추출

[[1]]
[1] "곽도성"

- 대문자 추출할 땐 [A-Z]를 이용한다.
- 제외할 땐 [^a-z]
- 영문자는 일단 제외하고 남은 것중 4글자 추출
  - [^a-z]{4}  , 남은 것중 문자종류 상관없이 4글자 추출

---

- 한 개의 숫자와 단어 관련 정규표현식

In [171]:
jm = '12344-125215'
str_extract(jm,'[0-9]{5}-[0-9]{2,}')

[1] "12344-125215"

In [172]:
str_extract_all(jm,'\\d{5}-\\d{6}')

[[1]]
[1] "12344-125215"

In [173]:
string = 'rhkrehtjddms123 dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlekrhkrehtjd.'

In [174]:
str_extract_all(string,'\\w{3,}')
# 3글자 이상의 단어만 추출, 허나 특수문자는 포함하지 않는다.

[[1]]
[1] "rhkrehtjddms123"  "rhdqnfmf444"      "Rh곽도성"         "xhdekfgkf"       
[5] "rjtdlekrhkrehtjd"

In [175]:
str_length(string)

[1] 64

In [176]:
# 문자열 내에서 특정 문자열의 첫 번째 index 시작과 끝
str_locate(string,'rhkrehtjd')
# 문자열 내에서 특정 문자열의 모든 위치의 index 시작과 끝
str_locate_all(string,'rhkrehtjd')

start end
[1,] 1     9

[[1]]
     start end
[1,]     1   9
[2,]    55  63

---

- 부분 문자열 만들기

In [177]:
string

[1] "rhkrehtjddms123 dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlekrhkrehtjd."

In [178]:
sub = str_sub(string,1,length(string)-20)
sub

[1] "rhkrehtjddms123 dl rhdqnfmf444 Rh곽도성 xhdekfgkf"

- 대소문자 변경

In [179]:
change = str_to_upper(string)
change

[1] "RHKREHTJDDMS123 DL RHDQNFMF444 RH곽도성 XHDEKFGKF RJTDLEKRHKREHTJD."

In [180]:
change = str_to_lower(string)
change

[1] "rhkrehtjddms123 dl rhdqnfmf444 rh곽도성 xhdekfgkf rjtdlekrhkrehtjd."

- 문자열 교체

In [181]:
string

[1] "rhkrehtjddms123 dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlekrhkrehtjd."

In [182]:
rep1 = str_replace(string,'123','dl')
rep1
# 123을 dl로 변경

[1] "rhkrehtjddmsdl dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlekrhkrehtjd."

- 문자열 결합

In [183]:
str_c(string,rep1)

[1] "rhkrehtjddms123 dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlekrhkrehtjd.rhkrehtjddmsdl dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlekrhkrehtjd."

In [184]:
str_c(string,'1111111111111')

[1] "rhkrehtjddms123 dl rhdqnfmf444 Rh곽도성 xhdekfgkf rjtdlekrhkrehtjd.1111111111111"

- 문자열 분리

In [185]:
a=str_split(string,'r')
# r기준으로 문자열 분리
a

[[1]]
[1] ""                               "hk"                            
[3] "ehtjddms123 dl "                "hdqnfmf444 Rh곽도성 xhdekfgkf "
[5] "jtdlek"                         "hk"                            
[7] "ehtjd."

In [186]:
mode(a)
class(a)

[1] "list"

[1] "list"

- 문자열 합치기

In [187]:
new = c('asd','asdadfd','asds','aqefsd')
# 콤마를 기준으로 문자열 벡터 합치자
join = paste(new,collapse = ',')
join

[1] "asd,asdadfd,asds,aqefsd"

- 벡터 객체로 반환해준다
- 예를 들면 문자열 100개가 1개씩 우너소를 차지하는 벡터 객체를 대상으로 paste()함수를 적용하여 1개의 원소로 축소가 가능하다.
- 따라서 방대한 자료를 분석하기 위해서 실습 예에서와 같은 방법으로 처리 단위를 축소한다면 빅데이터를 효율적으로 처리할 수 있다.